### ISSUE TITLE
Retroalimencación

### ISSUE THREAD

**Issue by Guirdo** [ing3gonzalez/ing3gonzalez.clonegoogle.io#1]
Con respecto a la siguiente linea, aunque este `<input>` tiene un comportamiento parecido a un botón normal, los `<input type="submit">` se utilizan para confirmar un formulario.

https://github.com/ing3gonzalez/ing3gonzalez.clonegoogle.io/blob/bb08482aca8ecf2fc0bd35e9e595a36d8175d019/index.html#L20

Pero lo que sucede en la página original de google, este botón es un enlace a otra página, aquí te recomendaría utilizar un elemento `<a>` porque llevaría al usuario a otra url.

```html
<li> <a href="#">Iniciar Sesión</a></li>
```

Solo quedaría que en la linea 59 de tu CSS cambiaras el ultimo selector, que es un `input`, por un `a`, y agregar un `padding` para que visualmente pareciera un botón.

```css
header nav .menu-sup.menu-sup li:nth-child(4) a
{
   /* resto del código */
    padding: 0.5rem;

}

```
